global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using ExercicioAPIStella.Data.Repositories;
global using ExercicioAPIStella.Data.Context;
global using ExercicioAPIStella.Domain.Entities;
global using ExercicioAPIStella.Domain.Interfaces;
global using Microsoft.EntityFrameworkCore;
global using Bogus;
global using Bogus.Extensions.Brazil;
global using Microsoft.Extensions.DependencyInjection;
